#!/bin/bash                                                                                                                                    
                                                                                                                                               
IP=127.0.0.1                                                                                                                                   
EXE=./HEEDS

# There must be at least 4 arguments
if [ -z "$4" ]; then
    echo "USAGE: $0 UNIV YEAR TERM ACTION"
    exit 
fi

# University/Format must be the same as in RAWDATA
declare -a  University_Code=( UPLB ISU  CSU  KASC CSU-Demo DEMO )
declare -a  University_Port=( 600  590  580  570  560      550  )
declare -a      Format_Code=( UPLB SIAS SIAS SIAS SIAS     UPLB )
# Action/Port_Number combination must be the same as in nginx.conf
declare -a      Action_Code=( Classlists Advising Gradesheets Schedules )
declare -a      Port_Number=( 10         20       30          40 )

# Search for matching univesity
for univ in ${!University_Code[*]}
do
    if [ $1 = ${University_Code[$univ]} ]; then
        #printf "%4d: %s\n" $univ ${University_Code[$univ]}
        # Search for matching Action 
        for action in ${!Action_Code[*]}
        do
            if [ $4 = ${Action_Code[$action]} ]; then
                #printf "  %4d: %s\n" $action ${Action_Code[$action]}
                if [ -x $EXE\_${Format_Code[$univ]}\_${Action_Code[$action]} ]; then
                    spawn-fcgi -a $IP -p ${University_Port[$univ]}${Port_Number[$action]} -- $EXE\_${Format_Code[$univ]}\_${Action_Code[$action]} $*
                else
                    echo Not found: $EXE\_${Format_Code[$univ]}\_${Action_Code[$action]}
                fi
                exit
            fi
        done
        echo "Action '$4' not recognized"
        exit
    fi
done
echo "University '$1' not recognized"
